# Cloudflare UAT Configuration
name = "ccsb-v3-uat"
main = "dist/worker.js"
compatibility_date = "2024-08-01"
compatibility_flags = ["nodejs_compat"]

# Environment variables for UAT
[vars]
NODE_ENV = "uat"
LOG_LEVEL = "debug"
APP_VERSION = "1.0.0-uat"

# R2 bucket for UAT
[[r2_buckets]]
binding = "R2"
bucket_name = "ccsb-screens-uat"

# D1 database for UAT
[[d1_databases]]
binding = "DB"
database_name = "ccsb-db-uat"
database_id = "uat-ccsb-db"

# KV namespace for UAT logs
[[kv_namespaces]]
binding = "LOGS"
id = "uat-logs"

# Pages configuration for UAT
[pages]
name = "ccsb-v3-uat"
project_name = "ccsb-v3-uat"

# Workers configuration for UAT
[workers_dev]
name = "ccsb-v3-uat-worker"

# Routes for UAT
[[routes]]
pattern = "uat.ccsb.example.com/*"
zone_name = "ccsb.example.com"

# Environment-specific settings
[env.uat]
name = "ccsb-v3-uat"
vars = { NODE_ENV = "uat", LOG_LEVEL = "debug" }

# Cron triggers for UAT (if needed)
[triggers]
crons = [
  "0 */6 * * *",  # Every 6 hours
  "0 0 * * *"     # Daily at midnight
]


